---
.github/workflows/ci.yaml:
  buildArgs: []
  checkoutTestApplications: false
  env:
    - DOCKER_IMAGE: adorsys/
      TAG: latest
      DIR: .

.github/CODEOWNERS:
  usernames:
    - '@jkroepke'

.dockerfilelintrc:
  rules:
    latest_tag: 'off'
