---
.github/workflows/ci.yaml:
  buildArgs: []
  checkoutTestApplications: false
  schedule: '30 5 * * *'
  pushCondition: "github.ref == 'refs/heads/master'"
  env:
    - DOCKER_IMAGE: adorsys/
      TAG: latest
      DIR: .
  customActionWorkflow: ''

.github/CODEOWNERS:
  usernames: []

.dockerfilelintrc:
  rules:
    latest_tag: 'off'
